# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a2ef5d5efec46d09a94fa29002b39acd1df5abde65516d6cca44b1e8cc83509421d77656433cc5ce86a4da77d0a964bae6ffd26af56ea5082e3ba2cbc9859c8e

test:
  secret_key_base: 216eed3d46b433eafe7f1d72680a5348d511284e49adf0af803d34fe4853919c6350b6a3e0b9f6a36c235321ee68323ee2e8ed8d755ca4e772bd1b7b1429bc4b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
